config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.create(recipe_params)
    redirect_to recipes_path(@recipes)
  end

  def index
    @recipes = Recipe.all
  end


  private

  def recipe_params
     params.require(:recipe).permit(:title, :description)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quizz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<br />
<br />
<div>
  <h1>Recipes</h1>
  <% @recipes.each do |t| %>
    <li> <%= t.title %></li>
      <ul>- <%= t.description %> </ul>
  <% end %>
  
</div>

app/views/recipes/new.html.erb
<br />
<div class="my-form col-10 offset-1">
  <h1>Add New Recipe</h1>
  <%= simple_form_for @recipe, url: recipes_path do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <br />
    <%= f.submit "Create", class: 'btn btn-primary' %>
    <% end %>
    <br />
  </div>

app/views/static_pages/home.html.erb
<div>
  <div class="my-term">
    <h1> Ready to Taste the World!</h1>
    <h2> - Cook with us - </h2>
  </div>
  <p>
    <h3>All our effort is to bring dozens of different types of world’s tastes into your kitchen. Many more tastes are yet to come. Stay tuned!</h3>
  </p>
  <br />
  <%= link_to 'Show Recipes', recipes_path, class: 'btn btn-success' %>
  <%= link_to 'Create a new Recipe', new_recipe_path, class: 'btn btn-success' %>
</div>